<a href="https://colab.research.google.com/github/19PA1A0298/AI-lab/blob/master/Exp_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# "Experiment No 1: Numpy"

## i) Different ways to create Numpy arrays

In [6]:
import numpy as np
a=np.array([10,20,30])
print(a)

[10 20 30]


In [7]:
a=np.array([[10,20,30],[11,12,13]])
print(a)

[[10 20 30]
 [11 12 13]]


 ## ii)Add,Remove, Modify elements in array

 ### Add

In [8]:
a=np.array([1,2,3])
b=np.append(a,[40,50,60])
print (b)

[ 1  2  3 40 50 60]


### Remove

In [9]:
c=np.delete(a,2)
print(c)

[1 2]


### Modify

In [11]:
c[c<2]=-1
print(c)

[-1  2]


 ## iii) Arthemetic operations on Numpy array

In [14]:
import numpy as np
x=([1,2,3])
y=([2,1,4])
num_sum=np.add(x,y)
num_diff=np.subtract(x,y)
num_quo=np.divide(x,y)
num_mod=np.mod(x,y)
num_pow=np.power(x,y)
print(num_sum)
print(num_diff)
print(num_quo)
print(num_mod)
print(num_pow)

[3 3 7]
[-1  1 -1]
[0.5  2.   0.75]
[1 0 3]
[ 1  2 81]


## iv) Slicing and iterating of Numpy arrays

 ### Slicing

In [15]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1:4])

[2 3 4]


### Iterating

In [17]:
for a in arr:
 print(a)

1
2
3
4


## v)Matrix operations on Numpy arrays

In [19]:
import numpy as np
x=np.array([[1,4],[2,3]])
y=np.array([[6,9],[7,8]])
print(np.add(x,y))
print(np.subtract(x,y))
print(np.divide(x,y))

[[ 7 13]
 [ 9 11]]
[[-5 -5]
 [-5 -5]]
[[0.16666667 0.44444444]
 [0.28571429 0.375     ]]
